version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: circleci/node:browsers  # Pre-configured Node.js image with browsers

    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /path/to/your/service_account_key.json  # Replace with actual path (use environment variable later)

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install  # Adjust if you use a different package manager

      - run:
          name: Build React application
          command: npm run build  # Replace with your build command (e.g., npm run build)

      - run:
          name: Deploy to GCE
          command: ./deploy.sh

workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy
